[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# We need to tell the Netlify frontend where the Railway backend is located.
# You will set VITE_API_URL in Netlify's environment variables.
